# Generated by Django 5.2 on 2025-05-02 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="watch",
            index=models.Index(fields=["seller"], name="api_watch_seller__c03e8d_idx"),
        ),
        migrations.AddIndex(
            model_name="watch",
            index=models.Index(
                fields=["category"], name="api_watch_categor_e2ed43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watch",
            index=models.Index(
                fields=["condition"], name="api_watch_conditi_5cbf45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watch",
            index=models.Index(fields=["price"], name="api_watch_price_fbdf59_idx"),
        ),
        migrations.AddIndex(
            model_name="watch",
            index=models.Index(
                fields=["created_at"], name="api_watch_created_dfc230_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watch",
            index=models.Index(
                fields=["seller", "price"], name="api_watch_seller__3de7b1_idx"
            ),
        ),
    ]
